In [649]:
import torch
import matplotlib.pyplot as plt
%matplotlib inline
import numpy
import torch.nn.functional as F

In [650]:
# downloading our dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2025-09-01 19:18:49--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.


python(80581) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.


HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.4’

input.txt.4         100%[===================>]   1.06M  --.-KB/s    in 0.05s   

2025-09-01 19:18:49 (20.5 MB/s) - ‘input.txt.4’ saved [1115394/1115394]



In [651]:
with open('./input.txt','r',encoding='utf-8') as f:
    text = f.read()
print("lenth of dataset is:",len(text))

lenth of dataset is: 1115394


In [652]:
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [653]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [654]:
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[n] for n in l])

In [655]:
decode([4])

'&'

In [656]:
print(encode('hii there'))

[46, 47, 47, 1, 58, 46, 43, 56, 43]


In [657]:
decode(encode('hii there'))

'hii there'

In [658]:
data = torch.tensor(encode(text),dtype=torch.long)
print(data.shape,data.dtype)
print(data[:100])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [659]:
# Hyperparmeters
batch_size = 64
vocab_size = len(chars)
block_size = 16
max_iters = 3000
eval_intervals = 300
learning_rate = 1e-3
n_embd = 64

In [660]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [661]:
len(val_data)/len(train_data) * 100

11.111177521830864

In [662]:
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43])

In [663]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f'When input is: {context}, The output is {target}')

When input is: tensor([18]), The output is 47
When input is: tensor([18, 47]), The output is 56
When input is: tensor([18, 47, 56]), The output is 57
When input is: tensor([18, 47, 56, 57]), The output is 58
When input is: tensor([18, 47, 56, 57, 58]), The output is 1
When input is: tensor([18, 47, 56, 57, 58,  1]), The output is 15
When input is: tensor([18, 47, 56, 57, 58,  1, 15]), The output is 47
When input is: tensor([18, 47, 56, 57, 58,  1, 15, 47]), The output is 58
When input is: tensor([18, 47, 56, 57, 58,  1, 15, 47, 58]), The output is 47
When input is: tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47]), The output is 64
When input is: tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64]), The output is 43
When input is: tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43]), The output is 52
When input is: tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52]), The output is 10
When input is: tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10]), The output

In [664]:
torch.manual_seed(42)
def get_batch(split:str):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data)-block_size,(batch_size,))
    x = torch.stack([data[i:i+block_size]for i in ix])
    y = torch.stack([data[i+1:i+block_size+1]for i in ix])
    return x,y

xb,yb = get_batch('train')
print("X's",xb.shape)
print("Y's",yb.shape)

X's torch.Size([64, 16])
Y's torch.Size([64, 16])


In [678]:
import torch.nn as nn

class Head(nn.Module):
    '''One head of self-attention'''

    def __init__(self, head_size) -> None:
        super().__init__()
        self.head_size = head_size
        # initialse each q,k,v vector as (n_embd,head_size) as we want each of these to interact with each token which itself is represented by a (65dimension vector) 1 T = 65, so anything that
        # needs to interact with 1 T must be, 65 by x
        self.key = nn.Linear(n_embd,head_size,bias=False) 
        self.query = nn.Linear(n_embd,head_size,bias=False)
        self.value = nn.Linear(n_embd,head_size,bias=False)
        self.register_buffer('tril',torch.tril(torch.ones(block_size,block_size)))

    def forward(self,x):
        B,T,C = x.shape # B,T,C
        k = self.key(x)  # B,T,C 
        q = self.query(x) # B,T,C
        v = self.value(x) # B,T,C

        wei = q @ k.transpose(-2,-1) * (self.head_size**-0.5) # B,T,C @ B,C,T => # B,T,T #we also a add a normalisation term 
        wei = wei.masked_fill(self.tril[:T,:T]==0,float('-inf')) # type: ignore # B,T,T
        wei = F.softmax(wei,dim=-1) # B,T,T

        out = wei @ v # B,T,T @ B,T,C => B,T,C

        return out        

class MultiHeadAttention(nn.Module):
    '''Multiple heads of self-attention'''

    def __init__(self,num_heads,head_size) -> None:
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
    
    def forward(self,x):
        return torch.cat([h(x) for h in self.heads],dim=-1)

class FeedForward(nn.Module):
    '''Simple linear layer followed by a non-linearity'''

    def __init__(self, n_embd) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd,4*n_embd),
            nn.ReLU(),
            nn.Linear(4*n_embd,n_embd)
        )

    def forward(self,x):
        out = self.net(x)
        return out

class Block(nn.Module):
    '''Simple linear layer followed by a non-linearity'''
    
    def __init__(self,n_embd,n_head) -> None:
        super().__init__()
        head_size = n_embd//n_head
        self.sa = MultiHeadAttention(n_head,head_size) #i.e 4 heads of 8-dimensional heads
        self.ffwd = FeedForward(n_embd)
    
    def forward(self,x):
        x = self.sa(x)
        x = self.ffwd(x)
        return x


class BigramLanguageModel(nn.Module):
    
    def __init__(self) -> None:
        super().__init__()
        # we embedd the tokens
        self.token_embedding_table = nn.Embedding(vocab_size,n_embd) #n_embd = C 
        self.position_embedding_table =  nn.Embedding(block_size ,n_embd)
        self.blocks = nn.Sequential(
            Block(n_embd,4),
            Block(n_embd,4),
            Block(n_embd,4)
        )
        self.lm_head = nn.Linear(n_embd,vocab_size) #the last linear layer to map back to vocab size

    def forward(self,idx,targets=None):
        B , T = idx.shape
        # we grab the corresponding embeddings
        token_embd = self.token_embedding_table(idx) # (B,T,C)
        pos_embd = self.position_embedding_table(torch.arange(T))
        x = token_embd + pos_embd #addition as we're just adding in the context of position
        x = self.blocks(x)
        logits = self.lm_head(x) # (B,T,vocab_size)
        
        if targets is None:
            loss = None
        else:
            B,T,C = logits.shape
            logits = logits.view(B*T,C)
            targets = targets.view(B*T)

            loss = nn.functional.cross_entropy(logits,targets)
        
        return logits,loss
    
    def generate(self,idx,max_tokens):
        for _ in range(max_tokens):
            # when our generation grows longer than block_size, we would still want to feed in 8 characters at a time, as this ensures we never run out of scope in our embedding table which is (block_size ,n_embd)
            # so we clip the idx, to only contain the last 8 tokens or whatever blocks_size we chose
            idx_cond = idx[:, -block_size:] 
            logits,loss = self(idx_cond)
            logits = logits[:,-1,:] # only get the last logit
            probs = nn.functional.softmax(logits,dim=-1)
            idnext = torch.multinomial(probs,num_samples=1)
            idx = torch.cat((idx,idnext),dim=1)
        return idx

    # def __repr__(self):
    #     return f'BigramLanguageModel with {self.token_embedding_table}'


m = BigramLanguageModel()
out,loss = m(xb,yb)
print(out.shape)
print(f'{loss.item():.4f}')

torch.Size([1024, 65])
4.1840


In [ ]:
m

In [667]:
2.4065747261047363

2.4065747261047363

In [679]:
optimizer = torch.optim.AdamW(m.parameters(),lr = learning_rate)

In [693]:
for steps in range(10000):

    xb,yb = get_batch('train')

    logits,loss = m(xb,yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
print(loss.item())

1.5698319673538208


In [696]:
sum(p.numel() for p in m.parameters())

145537

In [694]:
ix = torch.zeros((1,1),dtype=torch.long)
print((decode(m.generate(ix,1000)[0].tolist())))


And thus dust by hispare a ve is the us invillains,
Is fly here Afries, proud of grief! Marcius hurrona and that.
this lales, in the east,
No mean
Are that let with this deal unstag give,
And thy nightis bed?

CLADET:
Here, good we wars: who say-beloved,
Wherefore, must be not not what the's us heare,
The temppeyes in here comfortal of who, Julish. I would loss to kisdome; 'em the state my rood
The city, take up silenter shower end queen,

Letter He, then those direct ree
ag
noll hof our vage,
And your me: is Green to thief he's me, news is
hyn.  years and says, the
mortal'd watere mount forth hinforcely, plebble pellsity,
How to'l and of can the dead bid not these unting me cambere
 Citizen:
I that bendersate
Wranking from me you, Sign'd unthreat faveys me: He nome of morrow he mine own weal,
Or rain a king: sir far that did jrued,
Whit for shave deal finger as
Mine of my feast,
Shepherd strength.

Lesell
Of thy liftgly, his own amalk 'departimes
Well hit resee is fogether;
And, ease

# Below is just some starter code to help us understand some concepts and is not relevant to the model above.

In [671]:
import numpy as np
ls = np.random.randint(0,10,(5,5))
ls

array([[5, 1, 2, 2, 0],
       [9, 6, 9, 7, 1],
       [8, 3, 4, 2, 2],
       [5, 3, 6, 2, 6],
       [2, 4, 2, 3, 3]])

In [672]:
ls[:,-3:]

array([[2, 2, 0],
       [9, 7, 1],
       [4, 2, 2],
       [6, 2, 6],
       [2, 3, 3]])

In [673]:
ix = torch.zeros((1,1),dtype=torch.long)
for i in range(100):
    idx_cond = ix[:, -block_size:]
    logits = m.forward(idx_cond)[0]
    logits = logits[:,-1,:]
    probs = nn.functional.softmax(logits,-1)
    idnext = torch.multinomial(probs,num_samples=1)
    ix = torch.cat((ix,idnext),dim=1)
print(ix.shape)
print(decode(ix[-1].tolist()))

torch.Size([1, 101])

rtee e te th toresg f onsr ne fhtir insto msul D fhils,on i
NMHG IGtc
G
TUSNEAsoe
a!or, IroCl. T oim


In [674]:
decode([ 0, 31])

'\nS'

In [675]:
idx = torch.randint(0,100,(2,5))
idnext = torch.tensor([[2,1],
                       [2,2]])
idx = torch.cat((idx,idnext),dim=1)
idx

tensor([[63, 91, 69, 28, 18,  2,  1],
        [61, 19, 12, 79, 75,  2,  2]])

In [676]:
tokens = torch.randint(0,65,(4,8))
embedding_matrix = torch.randn(65,65,requires_grad=True)
final_matrix = nn.functional.embedding(tokens, embedding_matrix)
final_matrix.shape

torch.Size([4, 8, 65])